### ISSUE TITLE
new commit causing deployment failure

### ISSUE THREAD

**Issue by manojsundaram** [asdaraujo/edge2ai-workshop#25]
Haven't had time to troubleshoot this yet, but the same configs were working last week before i pulled in the latest commit

```
Mon Jun 29 02:41:14 2020
Cmd ID: 1546333147, Name: ClusterTemplateImport, Status: FAILED (java.lang.IllegalArgumentException: Unknown configuration attribute 'xml.authorizers.userGroupProvider.composite-configurable-user-group-provider.property.User Group Provider 1' for service (type: 'NIFI', name: 'nifi').)
 +- Cmd ID: 1546333155, Name: DeployParcels, Status: Succeeded (The Following parcels successfully activated : Anaconda-5.1.0.1,CDH-7.1.1-1.cdh7.1.1.p0.3266817,CDSW-1.7.1.p1.1850946,CFM-2.0.1.0,FLINK-1.10.0-csa1.2.0.0-cdh7.1.1.0-326-2901802.) (Cluster: OneNodeCluster)
Traceback (most recent call last):
  File "/tmp/resources/create_cluster.py", line 347, in <module>
    CLUSTER_CREATOR.create_cluster(options.template)
  File "/tmp/resources/create_cluster.py", line 286, in create_cluster
    raise RuntimeError('Failed to deploy cluster template')
RuntimeError: Failed to deploy cluster template
```

**Comment by manojsundaram** [comment]
This is the template and configuration where the deployment fails.

`https://github.com/asdaraujo/edge2ai-workshop/blob/master/setup/terraform/resources/templates/nifi.json` 

`            {
              "name": "xml.authorizers.userGroupProvider.composite-configurable-user-group-provider.property.User Group Provider 1",
              "value": "cm-user-group-provider</property><property name=\"User Group Provider 2\">shell-user-group-provider"
            }`

**Comment by manojsundaram** [comment]
Fixed the issue by replacing the below from nifi.json template. I am not sure if this is a bug in the template or the configuration name on CM has changed since 

**From:**
`xml.authorizers.userGroupProvider.composite-configurable-user-group-provider.property.User Group Provider 1`

**To:**
`xml.authorizers.userGroupProvider.composite-user-group-provider.property.User Group Provider 1`
